name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test

      - name: Package application
        run: mvn package
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: afshin28
          password: 25295030a.k
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: afshin28/spring-argocd-k8s:${{ github.sha }}
  promote-to-dev-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          echo "promoting into dev environment!"
          git config --global user.email afshin.karimi28@gmail.com && git config --global user.name afshin.karimi28
          echo "cloning config repo k8s-manifest"
          git clone https://oauth2:${{ secrets.GH_PAT }}@github.com/${{ github.repository_owner }}/k8s-manifest.git
          cd k8s-manifest
          echo "checkout main branch"
          git checkout main
          echo "Update image tag in deployment.yaml"
          sed -i "s,image:.*image-name:.*,image: afshin28/spring-argocd-k8s:${{ github.sha }}," resource/deployment.yaml
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git status
          git log -n 1
          git push